test notify

diff --git a/.github/workflows/notifysteprslt.yml b/.github/workflows/notifysteprslt.yml
--- a/.github/workflows/notifysteprslt.yml
+++ b/.github/workflows/notifysteprslt.yml
@@ -14,16 +14,17 @@ jobs:
          mvn deploy| grep 'ERROR' | tee mvnrst.log
          echo "::set-output name=mvndeployrst::$(cat mvnrst.log)"
          result_code=${PIPESTATUS[0]}
-         exit $result_code
-      - name: Notify about failure if last step failed
-        env:
-          check: ${{ contains(steps.maven-deploy.outputs.mvndeployrst, 'ERROR') }} 
-        run: |
-          echo "THE RESULT FROM CHECK IS"
-          echo ${check}
-          echo "THIS IS THE RESULT FROM LAST STEP TO NOTIFY"
-          echo ${{ steps.maven-deploy.outputs.mvndeployrst }}
-      - name: Notify about other failure
+         exit 1
+#         exit $result_code
+#      - name: Notify about failure if last step failed
+#        env:
+#          check: ${{ contains(steps.maven-deploy.outputs.mvndeployrst, 'ERROR') }} 
+#        run: |
+#          echo "THE RESULT FROM CHECK IS"
+#          echo ${check}
+#          echo "THIS IS THE RESULT FROM LAST STEP TO NOTIFY"
+#          echo ${{ steps.maven-deploy.outputs.mvndeployrst }}
+      - name: Notify failure on condition
         if: ${{ failure() }}
         run: |
           if [[ ${{ contains(steps.maven-deploy.outputs.mvndeployrst, 'ERROR') }} == true ]]; 
