Test random failure

diff --git a/.github/workflows/randomfailure.yml b/.github/workflows/randomfailure.yml
--- a/.github/workflows/randomfailure.yml
+++ b/.github/workflows/randomfailure.yml
@@ -11,4 +11,11 @@ jobs:
         run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
       - name: Pass or fail
         run: |
-          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
+          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; 
+           then 
+              echo "notify it was success"
+              exit 0; 
+          else 
+              echo "notify it fail"
+              exit 1; 
+          fi
